### ISSUE TITLE
QRoute.withChild Navigation issue

### ISSUE THREAD

**Issue by ajaylg** [SchabanBo/qr_samples#1]
Hii @SchabanBo 
I referred this example https://github.com/SchabanBo/qr_samples/blob/main/lib/common_cases/dashboard.dart
and created the same structure like signup, login, and Dashboard(with child route) 
I have a sidebar in my site that has sub-routes like Dashboard/info, Dashboard/contact ..etc when I click those items it navigates to the corresponding page, in my case this scenario does not work sometimes 

issue faced:
navigate to child-1
navigate to child-2
navigate to child-3
This child1 roue,child2 route,child3 route navigations are in **static fixed** sidebar
then I navigate to child-1 but it navigates to child-2, child pages did not get Refresh sometimes
routing Sometimes not works in QRoute.with child

In Each child page I call API in init state. but sometimes navigations not starts from init state so i have to manually refresh whole page to recall API

**Comment by SchabanBo** [comment]
Fixed with 1.2.0
