### ISSUE TITLE
Routing Animation Issue

### ISSUE THREAD

**Issue by rajat8527** [SchabanBo/qr_samples#2]
Hi @SchabanBo 

Everything worked pretty smooth for me but the slide animation that takes place while routing makes that transition look bad and laggy. If there would be an option of either removing that animation completely or replacing it with some other animation then it would be great.

**Comment by SchabanBo** [comment]
HI @rajat8527 ,
you can use [Page Transition](https://github.com/SchabanBo/qlevar_router#page-transition) to do so.
use `QCustomPage` to define your own one

**Comment by rajat8527** [comment]
It worked, thanks :)
